### ISSUE TITLE
Texture2D objects

### ISSUE THREAD

**Issue by nucky9** [Guevara-chan/Raylib-Forever#1]
When loading textures via LoadTexture(), they load correctly into openGl, but the returned Texture2D object seems to be filled in randomly. 

For instance: 

```nim
import raylib


InitWindow(400, 400, "test")
let texBunny = LoadTexture("wabbit_alpha.png")
echo texBunny.id
echo texBunny.width
echo texBunny.height
```

outputs:
137438953475
4294967328
2

Sorry, should mention this is 1.04 with no extra compiler flags

**Comment by Guevara-chan** [comment]
Dunno how I missed those typing delirium.
Fixed.
