### ISSUE TITLE
The .bycopy pragma should be added to objects that are passed to raylib by value

### ISSUE THREAD

**Issue by Ryan1729** [Guevara-chan/Raylib-Forever#13]
I raised [an issue on the Nim repo](https://github.com/nim-lang/Nim/issues/15899) because [I was having audio issues](https://github.com/Ryan1729/nim-raylib-forever-raylib-audio-bug) when trying to use Raylib-Forever. 

Andreas Rumpf replied there that the [`.bycopy` pragma](https://nim-lang.org/docs/manual.html#foreign-function-interface-bycopy-pragma) should be used on the object declarations. It appears like the pragma should be applied to [all objects that are passed by value](https://github.com/nim-lang/c2nim/issues/84), rather than by pointer.

Just to confirm, I tried that [fix](https://github.com/Ryan1729/nim-raylib-forever-raylib-audio-bug/commit/0b10692646b3f36928a28ce07a53a3516124d7f3) on the reduced bug reproduction, and it solved the audio playback problem.

**Comment by Guevara-chan** [comment]
Fixed on main. Merci.

**Comment by Ryan1729** [comment]
I can confirm the new version works. Thank you!
