### ISSUE TITLE
Downloaded files have compiler errors

### ISSUE THREAD

**Issue by Tuatarian** [Guevara-chan/Raylib-Forever#14]
Not quite capable of identifying how or why, but it is preventing me from using the raylib

**Comment by Guevara-chan** [comment]
`rlgl.nim(235, 24) Error: undeclared identifier: 'VertexBuffer'` - is it ? Just found those bug after latest revision.

**Comment by Guevara-chan** [comment]
Monkeypatched all found errors, re-download and check again.

**Comment by Tuatarian** [comment]
They seem to be gone, but when compiling with `nim c -r (file).nim` I get ```could not load: libraylib.so
(compile with -d:nimDebugDlOpen for more information)
Error: execution of an external program failed: '/mnt/d/Scripts/Misc/Nim/Nim/nim-chess/chess ```

**Comment by Guevara-chan** [comment]
Well, it happened already with everyone. Ever tried placing `libraylib.so` into **.exe**' workdir?
