### ISSUE TITLE
Compiling on linux fails to locate libraylib.so

### ISSUE THREAD

**Issue by Tuatarian** [Guevara-chan/Raylib-Forever#15]
full error:
`could not load: libraylib.so
(compile with -d:nimDebugDlOpen for more information)
Error: execution of an external program failed: '/mnt/d/Scripts/Misc/Nim/Nim/nim-chess/chess`

I've tried compiling the examples in the /examples directory

**Comment by Guevara-chan** [comment]
>Well, it happened already with everyone. Ever tried placing `libraylib.so` into **.exe**' workdir?

![image](https://user-images.githubusercontent.com/8768470/100640715-ceca6f80-3347-11eb-83c4-ac982547a914.png)

**Comment by Tuatarian** [comment]
I ended up having to use more absolute paths (./libraylib.so instead of just libraylib.so)
