### ISSUE TITLE
Compiling on Windows fails to locate libraylib.dll

### ISSUE THREAD

**Issue by Tuatarian** [Guevara-chan/Raylib-Forever#16]
`could not load: libraylib.dll
Error: execution of an external program failed: 'D:\Scripts\Misc\Nim\Nim\nim-chess\chess.exe '`

**Comment by Tuatarian** [comment]
You need to get the msvc 64 dlls from the raylib repo, not the mingw

**Comment by CIOSAI** [comment]
where are those?

**Comment by CIOSAI** [comment]
nvm found it, it's at [releases](https://github.com/raysan5/raylib/releases) for whoever reading this in the future
