### ISSUE TITLE
raylib.nim is not generated

### ISSUE THREAD

**Issue by HugoP707** [Guevara-chan/Raylib-Forever#19]
when trying to use the site, `rlgl.nim`, `raymath.nim` and `raygui.nim` are downloaded correctly. but there is no `raylib.nim`

**Comment by Guevara-chan** [comment]
Monkeypatched.

**Comment by Guevara-chan** [comment]
Fixed, check again.

**Comment by HugoP707** [comment]
It works fine, thanks.
