### ISSUE TITLE
Can I use these bindings natively?

### ISSUE THREAD

**Issue by rishavs** [Guevara-chan/Raylib-Forever#2]
Hi Guevara

In case I do not want to render a web app in Electron, can I still use your bindings to render the game natively?
How would one go about this?

**Comment by Guevara-chan** [comment]
Um... Yes ?
https://guevara-chan.github.io/Raylib-Forever/main.html

**Comment by rishavs** [comment]
oops. The compat section completely threw me off
"Raylib Forever was best tested with Chrome 80 and Electron, which is used to develop it.
It should work on any non-mechanical teapot that provides fetch and ES2019, though."
I thought we are somehow creating a webapp out of this.

I started with the same frustrations as you, none of the bindings are ever upto date or need enum conversions. I can confirm that the files are working for me. I can start a basic "hello world" raylib program. So thanks for this repo.
