### ISSUE TITLE
Example Page Is Serving Nim Files Instead Of Displaying

### ISSUE THREAD

**Issue by topcheese** [Guevara-chan/Raylib-Forever#4]
Hi, I'm on linux and using FF, but I don't have Nim installed on it.  When I click on your demo page, it just prompts me to download the Nim files.  The web server is not recognizing and executing Nim as script files.

**Comment by Guevara-chan** [comment]
Just clicked `/examples/` link and https://github.com/Guevara-chan/Raylib-Forever/tree/master/examples was opened in separate tab.

**Comment by topcheese** [comment]
This is the link you have on the front page. https://guevara-chan.github.io/Raylib-Forever/main.html

**Comment by Guevara-chan** [comment]
> This is the link you have on the front page. https://guevara-chan.github.io/Raylib-Forever/main.html

And **this** is exactly a link to Nim header files provider. Which provides Nim header files.  
Yes.

**Comment by topcheese** [comment]
I assumed it was a demo page  that rendered in the browser.  I didn't know that I had to have Nim installed for it to work  Thanks for the response!

**Comment by Guevara-chan** [comment]
> :.raylib headers for **Nim** anytime.:

Hm... 0 hints, I guess.

**Comment by topcheese** [comment]
Yeah, I'm just stupid.  I was putting way too much thought into it, and was thinking the page was suppose to do more ... seriously waaaaay too much thought.  I guess because it sort of looks like an error page asking you to try and reload the page.  I guess?
Sorry to bother you with a false report.  Thanks again!
